# src/Blogger/BlogBundle/Resources/config/routing.yml
BloggerBlogBundle_homepage:
    path:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET

BloggerBlogBundle_about:
    path:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

BloggerBlogBundle_blog_show:
    path:  /{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

BloggerBlogBundle_view_number:
    path:  /vled
    defaults: { _controller: BloggerBlogBundle:View:number }
    requirements:
        _method:  GET